src/core/pdg/include/DGBase.hpp
The original code has a bug - deref a dangling pointer - that will lead to undefined behavior.
Minimal example: https://godbolt.org/z/KcxKe3
=> DGBase properly solves optional deref bug

.gitignore, src/core/pdg/include/DGGraphTraits.hpp, src/tools/pdg_stats/src/PDGStats.cpp, src/tools/pdg_stats/src/PDGStats.hpp, src/tools/pdg_stats/src/Pass.cpp
- Added a new option to dump loop PDG after refined with SCAF
- Make LC deps thicker in the generated dot file
- Added some files into gitignore for better development
=> Add ability to dump Loop PDG after SCAF

src/tools/pdg_stats/src/PDGStats.cpp
In `pdg_stats`, the counting of stats are duplicated because there is an outer loop that goes through all functions, then in the inner loop, it goes through all the `programLoops`. Instead, this fix gets the forest from `programLoops`.
=> Remove duplicate count in PDG stats

src/core/pdg/src/PDGAnalysis_memory.cpp
Adding RAW dependency edge conservatively since WAW and WAR are
eventually disproved by SCAF. SCAF identifies this dependency to be
RAW. So conservatively adding RAW edge at the time of construction of
PDG
=> BUG FIX: Identifying wrong instructions as invariants in LICM pass

tests/regression/RAWCallToCall/test.cpp
Adding a test cases which would test for RAW dependency inserted
between two call instructions in a tight loop within the same
basic block. In case the dependency is not inserted then
two calls are treated as loop invariants and moved out of loop.
This would result in wrong output for the parallelized version
of code.
=> Regression test case for RAW dependency between two call instructions

src/core/pdg/include/noelle/core/DGBase.hpp, src/core/pdg/include/noelle/core/DGGraphTraits.hpp
Add an edge to id map to the DGBase. Also modified the DGPrinter to print the ID as a label to the edge.
This is used by the repl of CPF to render the PDG with the edge ID, an important feature to visualize and decide which edge to keep.
=> Add an optional edge->id map to DGbase

.clang-format, .githooks/Makefile, .githooks/hooks/pre-commit, Makefile
By running `make hooks` at the top level of the NOELLE repo you will install the pre-commit hook to run NOELLE's clang-format style on all C/C++ files to be committed.
=> git pre-commit hook for clang-format

src/core/loop_environment/include/noelle/core/LoopEnvironmentBuilder.hpp, src/core/loop_environment/src/LoopEnvironmentBuilder.cpp, src/core/task/include/noelle/core/Task.hpp, src/core/task/src/Task.cpp, src/tools/doall/src/DOALL.cpp, src/tools/helix/src/HELIX.cpp, src/tools/parallelization_technique/include/noelle/tools/ParallelizationTechnique.hpp, src/tools/parallelization_technique/src/ParallelizationTechnique.cpp
The PR adds the support to allow client to select part of environment variables. i.e, in reducible operations, the initial value, which is a live-in variable, doesn't need to be included into the task but can be later initialized with the identity value of that operation in the cloned task instead. Below is a breakdown of all the changes to different classes in NOELLE. Two clients, **DOALL** and **HELIX** has been modified to ignore the initial value while parallelized with reducible operations.
* public:
* apply: add lambda isSkippable to skip the initial value of reduction variable, and let skipped variables tacked by the task
* public:
* new constructor that takes a skippable lambda function as initial argument
* adjustDataFlowToUseClones: skip a value if it's a skipped environment …
=> Extend LoopEnvironment abstractions to allow client select partial of environment variables

src/core/scripts/installNOELLE.sh, src/core/scripts/noelle-meta-loop-clean, src/core/scripts/noelle-meta-pdg-clean, src/core/scripts/noelle-meta-prof-clean
Changes:
- Fixed previously discussed bug for noelle-meta-loop-clean and noelle-meta-pdg-clean erasing too much metadata.
- Added new command for cleaning profiler metadata. Nothing in master uses this yet but I use it on the nested parallelism, and since the metadata cleaning pass already has the code to do it I figured I'd tack it onto this.
=> Bugfix and new feature for metadata cleaning

src/tools/parallelizer/src/Pass.cpp
Temporary fix for issues caused by disregarding semantics of LLVM lifetime intrinsic instructions
=> Parallelizer: erase llvm lifetime intrinsics in modified functions

src/core/pdg_analysis/include/noelle/core/PDGAnalysis.hpp, src/core/pdg_analysis/src/PDGAnalysis.cpp, src/core/pdg_analysis/src/PDGAnalysis_memory.cpp
This pull request makes the following changes:
1. Fixing the bug of incorrectly querying getModRefInfo between two calls using `getModRefInfo(otherCall, call)` if `otherCall` is reachable from `call`
2. Adding an extra flag indicating whether `call` is also reachable from `otherCall` to reversely query the ModRefInfo to add missing dependencies
3. Adding dependencies only from `call` to `otherCall`. The dependencies from `otherCall` to `call` will be handled if `call` is reachable from `otherCall` as the analysis pass proceeds.
Regression Tests Result:
```
./scripts/condor_check.sh ;
################################### REGRESSION TESTS:
Checking the regression test results
All tests finished
7 new tests failed: 
regression_125/AliasAnalysisKillFlowBug -noelle-pdg-check -noelle-verbose=3 …
```
=> PDGAnalysis: fix missing dependences querying getModRefInfo between two calls

src/core/pdg_analysis/src/PDGAnalysis_memory.cpp
When querying `getModRefInfo(otherCall, call)` and get `Mod` result. If `call` is also reachable from `otherCall` and the reverse query also returns `Mod`. No matter if `(call == otherCall)`. There's only WAW data dependence from `call` to `otherCall`.
Regression test output:
```
./scripts/condor_check.sh ;
################################### REGRESSION TESTS:
Checking the regression test results
All tests finished
5 new tests failed: 
regression_124/AliasAnalysisKillFlowBug -noelle-pdg-check -noelle-verbose=3 -noelle-max-cores=8  -noelle-parallelizer-force -O1 -Xclang -disable-llvm-passes -O1
regression_126/AliasAnalysisKillFlowBug -noelle-pdg-check -noelle-verbose=3 -noelle-max-cores=8 -noelle-disable-loop-invariant-code-motion  -noelle-parallelizer-force -O1 -Xclang …
```
=> PDGAnalysis: optimization on dependence addition through getModRefInfo

src/tools/scripts/noelle-fixedpoint
We now check for error codes after each step of the pipeline to avoid infinite loops.
=> noelle-fixedpoint

src/tools/Makefile, src/tools/enablers/src/Enablers.cpp, src/tools/input_output/CMakeLists.txt, src/tools/input_output/src/CMakeLists.txt, src/tools/input_output/src/InputOutput.cpp, src/tools/input_output/src/InputOutput.hpp, src/tools/input_output/src/Pass.cpp, src/tools/scripts/installNOELLETools.sh, src/tools/scripts/noelle-io, src/tools/scripts/noelle-pre
- Added a new enabler, `noelle-io`, to make file accesses more amenable for parallelization.
- Currently, the only transformation implemented in `noelle-io` is replacing all `getc` with `getc_unlocked`.
- Since we will handle the synchronization manually, using the unlocked version of `getc` is safe without acquiring and releasing locks for files in runtime.
- The new enabler is tested on all test cases (https://github.com/arcana-lab/noelle/tree/master/tests) and benchmarks from https://github.com/arcana-lab/noelleGym.
- TODO: transformations that replace other `stdio` having an implicit locking mechanism.
=> Enabler: add a new enabler to make file accesses more amenable for parallelization

src/tools/input_output/src/InputOutput.cpp, src/tools/input_output/src/InputOutput.hpp
- Since we will handle the synchronization manually, using the unlocked version of stdio functions are safe without acquiring and releasing locks for files in runtime.
- References:
- https://github.com/arcana-lab/noelle/pull/82
- https://www.gnu.org/software/gnulib/manual/html_node/
- stdio functions that the IO Enabler will handle:
- `getc`
- `getcchar`
- `putc`
- `putchar`
- `clearerr`
- `feof`
- `ferror`
- `fflush`
- `fgetc`
- `fgets`
- `fileno`
- `fputc`
- `fputs`
- `fread`
- `fwrite`
- `fgetwc`
- `fgetws`
- `fputwc`
- `fputws`
- `getwc`
- `getwchar`
- `putwc`
- `putwchar`
=> Enabler: add transformations that replace more stdio having an implicit locking mechanism

src/tools/parallelizer/src/Parallelizer_loops.cpp, src/tools/scripts/noelle-parallelizer-singleloop
This PR fixes the policy with which loops with a parallel plan are selected in the `parallelizer` tool.
Also, `noelle-parallelizer-singleloop` now has a brief description of the error code (timed out | seg fault)
=> Parallelizer: fixed missing condition

tests/regression/DoallLastIteration/test.cpp
Pointers p, q, r access the 100th element, which is not part of the allocated memory objects.
=> Noelle: fix issue of DoallLastIteration testcase

src/tools/helix/src/HELIX_spiller.cpp, tests/regression/HelixSpillerIssue/test.cpp
Helix may insert load of spilled variables in the preheader of the loop.
Add one test case that could trigger this issue, and add the fix.
=> Helix Spiller Issue

src/core/Makefile, src/core/functions_manager/src/CMakeLists.txt, src/core/loop_content/src/CMakeLists.txt, src/core/loop_dependence_analyses/src/CMakeLists.txt, src/core/loop_sccdag_normalizer/src/CMakeLists.txt, src/core/may_points_to_analysis/CMakeLists.txt, src/core/may_points_to_analysis/include/noelle/core/MayPointsToAnalysis.hpp, src/core/may_points_to_analysis/src/CMakeLists.txt, src/core/may_points_to_analysis/src/MayPointsToAnalysis.cpp, src/core/may_points_to_analysis/src/MpaSummary.cpp, src/core/may_points_to_analysis/src/MpaUtils.cpp, src/core/may_points_to_analysis/src/MpaUtils.hpp, src/core/noelle/include/noelle/core/Noelle.hpp, src/core/noelle/src/CMakeLists.txt, src/core/noelle/src/Noelle.cpp, src/core/pdg_analysis/include/noelle/core/PDGAnalysis.hpp, src/core/pdg_analysis/src/PDGAnalysis.cpp, src/core/scripts/noelle-load, tests/condor/bin/runRegression.sh
1. Add an intra-procedural, flow-insensitive, field-insensitive may-points-to-analysis in src/core/may_points_to_analysis.
2. In src/core/pdg_analysis, replace AllocAA with this may-points-to-analysis to check alias info more precisely.
3. In src/core/pdg_analysis, remove some over-conservative dependences between LoadInst and print functions.
4. In tests/condor/bin/runRegression.sh, early quit if test case not exits.
=> Update may_points_to_analysis and pdg_analysis

src/tools/privatizer/include/Privatizer.hpp, src/tools/privatizer/src/GlobalToStack.cpp, tests/regression/PrivatizerIssue/test.cpp
Add the `PrivatizerIssue` testcase to trigger the incorrect logic in Privatizer::getInitProgramPoint, then add a fix.
To check that a global array is completely initialized, privatizer expects the following pattern, where the instruction `globalArray[i] = 20;` is called a initializer of `globalArray`.
```c
int globalArray[10];
void f() {
for (int i = 0; i < 10; i++) {
globalArray[i] = 20;
}
}
```
Privatizer didn't check initializers rigorously enough so that it would say `globalArray2[i] = 40;` is also a initializer, which is incorrect because `globalArray2` is not completely initialized.
```c
int globalArray2[10];
void f() {
for (int i = 0; i < 10; i++) {
if (i > 7) {
globalArray2[i] = 40;
}
}
}
```
=> Fix privatizer issue

src/tools/helix/src/HELIX_stepper.cpp
Bug with HELIX periodic variable logic when dealing with `i1` values, fixed.
=> Fixed bug with PeriodicVariableOutput regression test

src/core/loop_environment/src/LoopEnvironment.cpp
The wrong method gets called when getting the set of IDs of LiveOutVars.
=> [bug] Fixed a bug in loop environment

src/core/dg/include/noelle/core/DGEdge.hpp
The smallest-at-the-end rule strikes again
=> [DG] DGEdge type size reduction from 48 bytes to 40 bytes

src/core/dataflow/include/noelle/core/DataFlowEngine.hpp, src/core/dataflow/src/DataFlowEngine.cpp
1. Generalized dataflow engine applying for both forward and backward 
2. Deleted the previous `applyCustomizedForwad` and `applyBackward` functions, they both call the new generalized function `applyGeneralizedForward`
=> generalize the backward and forward dataflow engine

src/core/dg/include/noelle/core/DGBase.hpp
The function `DG<T>::getLeafNodes` in `DGBase.hpp` does the opposite of what its semantics suggest: 
- When `onlyInternal` is false, it only considers internal nodes  
- When `onlyInternal` is true, it considers all nodes
Swap the code within the if and else statements of `DG<T>::getLeafNodes`.
=> DGBase::getLeafNodes semantics mismatch

src/core/pdg_generator/src/IntegrationWithSVF.cpp
The `sfrander` pointer analysis gives an incorrect (NoAlias) result, which generates a smaller SCC and gets distributed through the `LoopDistribution` pass. This, in the end, results in a segfault of the test `LoopDistribution5`. This change disables `—sfrander` so that all `LoopDistribution5` regression tests can pass.
This bug has also been reported to SVF [here](https://github.com/SVF-tools/SVF/issues/1475) for help.
=> [svf] disable -sfrander pointer analysis

src/core/pdg_generator/src/IntegrationWithSVF.cpp
Re-enable sfrander pointer analysis since it has been fixed from SVF [here](https://github.com/SVF-tools/SVF/issues/1475).
=> [svf] re-enable sfrander pointer analysis

src/core/pdg_generator/CMakeLists.txt, src/core/pdg_generator/include/noelle/core/PDGGenerator.hpp, src/core/pdg_generator/src/PDGGenerator_metadata_cleanAndEmbedder.cpp, src/core/pdg_generator/src/PDGGenerator_metadata_cleaner.cpp
- Added private function `PDGGenerator::cleanPDGMetadata()` to the `PDGGenerator` class
- Added public function `PDGGenerator::cleanAndEmbedPDGAsMetadata(PDG *)` to the `PDGGenerator` class, which calls private functions `PDGGenerator::cleanPDGMetadata()` and `PDGGenerator::embedPDGAsMetadata(PDG *)`.
=> Implemented metadata cleaner and embedder of PDGgenerator

CMakeLists.txt, Makefile, bin/CMakeLists.txt, src/CMakeLists.txt
Now we need to enable z3 with `source /project/extra/z3/4.13.0/enable`
=> Fixed recompilation issues for `v14`

CMakeLists.txt, Kconfig, bin/noelle-config.in, src/CMakeLists.txt
This allows users to compile Noelle, SVF and SCAF through different cmake build types (e.g. Debug, Release, RelWithDebInfo)
=> Supporting compilation with different build types

README.md
When building NOELLE for v14 for the first time, cmake couldn't find z3. I fixed this by enabling z3, which I only knew to do from reading #157. That instruction should be somewhere more visible.
The error:
```
CMake Error at build/_deps/svf-src/CMakeLists.txt:115 (find_package):
Could not find a package configuration file provided by "Z3" with any of
the following names:
Z3Config.cmake
z3-config.cmake
Add the installation prefix of "Z3" to CMAKE_PREFIX_PATH or set "Z3_DIR" to
a directory containing one of the above files.  If "Z3" provides a separate
development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
make: *** [Makefile:17: build] Error 1
```
=> [doc] z3 as a prerequisite + Zythos instructions

src/core/ldg_generator/src/LoopAwareMemDepAnalysis.cpp, src/core/loop_iteration_space_analysis/src/LoopIterationSpaceAnalysis.cpp, src/core/loop_sccdag_attributes/src/SCCDAGAttrs.cpp, src/core/pdg_generator/src/IntegrationWithSVF.cpp, src/core/unique_ir_marker/include/arcana/noelle/core/IDToValueMapper.hpp, src/core/unique_ir_marker/include/arcana/noelle/core/UniqueIRMarker.hpp, src/core/unique_ir_marker/src/UniqueIRMarker.cpp, src/core/unique_ir_marker/src/UniqueIRVerifier.cpp, src/tools/pdg_stats/src/PDGStats.cpp, src/tools/scev_simplification/src/SCEVSimplification.cpp
All warnings originating from Noelle have been addressed.
Most of warnings however, come from SVF and SCAF. Since Noelle uses a specified branch for both SVF and SCAF, I added pragma diagnostics to suppress the known warnings originating from them.
There should be only one (spurious) warning in SCAF when compiling with clang 14.0.6.
This PR has been tested through Gino's [PR22](https://github.com/arcana-lab/gino/pull/22)
=> Fixed compile warnings

bin/tools/CMakeLists.txt, bin/tools/noelle-ldg-dot, src/tools/ldg_dot/CMakeLists.txt, src/tools/ldg_dot/src/LDGDot.cpp, src/tools/ldg_dot/src/LDGDot.hpp, src/tools/ldg_dot/src/Pass.cpp, src/tools/ldg_dot/src/Pass.hpp
Convert a loop dependence graph into a [DOT graph](https://graphviz.org/doc/info/lang.html). Particular attention is put to SCCs and loop-carried dependences. 
This tool is intended to replace the cumbersome `noelle-pdg`.
=> Tool: `noelle-ldg-dot`

src/core/ldg_generator/include/arcana/noelle/core/LDGGenerator.hpp, src/core/ldg_generator/src/LDGGenerator.cpp, src/core/noelle/include/arcana/noelle/core/Noelle.hpp, src/core/noelle/src/Noelle_dependences.cpp, src/core/noelle/src/Noelle_function.cpp, src/core/pdg_generator/include/arcana/noelle/core/PDGGenerator.hpp, src/core/pdg_generator/src/PDGGenerator.cpp
Custom `DependenceAnalysis`s can now be removed. This is for both symmetry with `addAnalysis` and is necessary when studying differences between analyses.
=> Added `removeAnalysis` to `Noelle`
